### ISSUE TITLE
Notice: GitHub Dependabot now natively supports this functionality.

### ISSUE THREAD

**Issue by connorhsm** [Makeshift/generate-dependabot-glob-action#44]
See [documentation here](https://github.blog/changelog/2024-06-25-simplified-dependabot-yml-configuration-with-multi-directory-key-directories-and-wildcard-glob-support/) on using globbing directly in `dependabot.yml`.

Please correct me if I am wrong, but I believe this action is now redundant.

**Comment by Denny-g6labs** [comment]
I can confirm that it somehow works. It's barely documented and the pattern only applies to folders it seems. You can't glob filenames (I'm not 100% sure about that).
How I use it:
```yaml
version: 2
updates:
  # Groups ALL npm dependency updates into a single weekly PR.
  - package-ecosystem: "npm"
    directories:
      - "/code/gui/dashboard" # Add other npm project directories here if you have more.
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "08:00"
      timezone: "America/Los_Angeles"
    groups:
      frontend-npm-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"

  # Groups ALL python dependency updates from across the repo into a single weekly PR.
  - package-ecosystem: "pip"
    directories:
      - "/"
      - "/code/lambda/**"
      - "/code/lambda_nested_stacks/**"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "08:00"
      timezone: "America/Los_Angeles"
    groups:
      python-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"

  # Groups ALL Go module updates from across the repo into a single weekly PR.
  - package-ecosystem: "gomod"
    directories:
      - "/code/lambda/**"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "08:00"
      timezone: "America/Los_Angeles"
    groups:
      go-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10

  # Dockerfile updates from across the repo; single weekly PR.
  - package-ecosystem: "docker"
    directories:
      - "/code/aws/3_main_infra/**/images"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "08:00"
      timezone: "America/Los_Angeles"
    # Group ONLY the marble images together.
    # Any other image will get its own PR by default.
    groups:
      docker-dependencies-marble:
        patterns:
          - "*marble*"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "direct"

  # Groups all GitHub Actions updates into a single monthly PR.
  - package-ecosystem: "github-actions"
    directory: "/" # This looks in the .github/workflows directory.
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 10

```

That groups all PIP requirements files together. It never groups Docker Images EXCEPT for Marble, where I want to have two images in one PR. At the beginning I used `"**/*"`, as documented here:
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/controlling-dependencies-updated#defining-multiple-locations-for-manifest-files
But then I got I timeout, maybe because I grouped so many files (Which were not `requirements.txt files`). Whatever...
